name: pages-build

on:
  push:
    branches: [main]
    # paths: [docs/**]
  pull_request:
    branches: [main]
    # paths: [docs/**]

env:
  PUPPETEER_PRODUCT: chrome

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2

      - name: Use Deno Latest Stable
        uses: denolib/setup-deno@v2
        with: { deno-version: vx.x.x }

      - name: Use Puppeteer Latest Stable
        run: deno run -A --unstable https://deno.land/x/puppeteer@9.0.2/install.ts

      - name: Build
        # run: deno run -A --unstable https://deno.land/x/booklet/lib/index.ts --bundle -f
        run: deno run -A --unstable ./lib/index.ts --bundle -f

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
          publish_dir: ./docs/.booklet
          # cname: example.com
