on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2

      - run: deno test ./packages/booklet/mod_test.ts
      - run: deno test ./packages/booklet-content/mod_test.ts
